# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

redirect:
    resource: "@AcmeDemoBundle/Controller/RedirectController.php"
    type:     annotation